return {
    prompt = "",
    current = " ",
    selected = "",
    close = "󰅖",
    modified = "",
    pinned = "",
    edit = "",
    buffer = "",
    search = "",
    whitespace = {
        tab = "»",
        space = "·",
        eol = "",
        nbsp = "␣",
    },
    fold = {
        open = "",
        close = "",
        sep = " ",
    },
    tree = {
        horizontal = "─",
        vertical = "│",
        expanded = "┐",
        node = "├",
        nodelast = "└",
    },
    files = {
        default = "",
        text = "",
        symlink = "",
    },
    file_status = {
        modified = "",
        readonly = "",
        hidden = "󰛑",
    },
    folder = {
        closed = "",
        open = "",
        empty = "",
        empty_open = "",
        symlink = "",
        symlink_open = "",
    },
    diff = {
        added = "",
        modified = "",
        removed = "",
    },
    diff_gutter = {
        add = "▊",
        change = "▊",
        delete = "",
        untracked = "▊",
    },
    gitsigns = {
        -- Change type
        added = "",
        modified = "",
        deleted = "",
        renamed = "➜",
        -- Status type
        untracked = "★",
        ignored = "◌",
        unstaged = "",
        staged = "✓",
        conflict = "",
    },
    todo = {
        default = "",
        warn = "",
        perf = "",
        bug = "",
        hack = "",
        test = "󰄉",
    },
    diagnostics = {
        error = "",
        warn = "",
        info = "",
        hint = "",
    },
    test = {
        ok = "",
        failed = "",
        running = "",
        skipped = "",
        watch = "",
        unknown = "",
    },
    symbols = {
        Text = "",
        Method = "",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Namespace = "",
        Package = "",
        Property = "",
        Unit = "󰑭",
        Value = "",
        String = "",
        Number = "",
        NumberHex = "󱊧",
        Boolean = "",
        Array = "",
        Object = "",
        Enum = "",
        Keyword = "",
        Snippet = "󰘦",
        Color = "",
        File = "󰈙",
        Reference = "󰈇",
        Folder = "󰉋",
        Key = ' ',
        Null = ' ',
        EnumMember = "",
        Constant = "",
        Struct = "󰙅",
        Event = "",
        Operator = "󰆕",
        TypeParameter = "",
        Spell = "",
    },
    filetypes = {
        php = "󰌟",
        phpunit = "󰙨",
        laravel = ""
    }
}
