[general]
ipc_socket = false

[env]
TERM = "xterm-kitty"

[font]
normal = { family = "IosevkaCustomNerdFont" }
bold = { style = "SemiBold" }
size = 16.0

offset = { x = 0, y = 4 }
glyph_offset = { x = 0, y = 2 }

[window]
decorations_theme_variant = "Dark"
padding = { x = 1, y = 1 }
# opacity = 0.98

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = false
cursor = { text = "#eceef4", cursor = "#767BA0" }
selection = { text = "CellForeground", background = "#5B5F7C" }
footer_bar = { foreground = "#eceef4", background = "#0C0D14" }
line_indicator = { foreground = "#eceef4", background = "#0E1019" }

[colors.primary]
foreground = "#eceef4"
background = "#0E1019"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#eceef4"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.search]
matches = { foreground = "#0E1019", background = "#767BA0" }
focused_match = { foreground = "#0E1019", background = "#F9E2AF" }
