
[env]
TERM = "xterm-256color"

[font]
#normal = { family = "JetBrains Mono NF", style = "Regular" }
normal = { family = "JetBrains Mono NF", style = "SemiBold" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.0

[window]
padding = { x = 2, y = 2 }
opacity = 0.99

[colors]
cursor = { text = "#0E1019", cursor = "#BAC2DE" }

[colors.primary]
foreground = "#eceef4"
background = "#0E1019"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"
