
--- LuaLS is weird and does not recognize builtin types
--- even tho it should. So define them as aliases
---@alias nil nil
---@alias any any
---@alias boolean boolean
---@alias string string
---@alias number number
---@alias integer integer
---@alias function function
---@alias table table
---@alias thread thread
---@alias userdata userdata
---@alias lightuserdata lightuserdata
